language: java

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.sonar/cache'

before_install:
  - export MAVEN_OPTS=-Xmx1024m

jdk:
  - oraclejdk9

branches:
  only:
    - master

script:
  - mvn clean package
