language: java

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.sonar/cache'

before_install:
  - export MAVEN_OPTS=-Xmx1024m

jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13

branches:
  only:
    - 2.x

install:
  - ./etc/travis-install.sh

script:
  - ./etc/travis.sh
