language: java

script:
  - mvn -Dlogback.configurationFile=logback-travis.xml clean package coveralls:report -P coverage

jdk:
  - oraclejdk8

branches:
  only:
    - master

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer
