language: java
sudo: required
dist: trusty
branches:
  only:
    - master
jdk:
  - oraclejdk8
script:
  - mvn -Dlogback.configurationFile=logback-travis.xml clean package coveralls:report -P coverage
