name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java_version: [1.8]
        os: [windows-latest, macOS-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - name: Prepare Build
        run: mvn -DskipTests=true clean install -q -pl '!docs,!examples'
      - name: Build
        run: mvn checkstyle:checkstyle package -P checkstyle -pl '!docs,!examples'
